// @generated by tools/generate-canonical-operation-binding.py; do not edit.
#[cfg(test)]
pub(super) const CONTRACT_SCHEMA: &str = "org.trillionnium.canonical-operation-binding.contract.v1";
#[cfg(test)]
pub(super) const CONTRACT_SHA256: &str = "e24a5029cbc545971dc8ca935754faa44df4406bcdc600c7e5fef3b7c8b48231";
pub(super) const CODEX_REPLAY_NAMESPACE: &str =
    trillionnium_os_types::agent_principal_registry::CODEX_STABLE_PRINCIPAL.replay_namespace;
pub(super) const SYSTEM_API_PROTOCOL: &str = "org.trillionnium.agent-system-api.v1";
pub(super) const SYSTEM_API_IDENTITY_VERSION: &str = "peer-bound-v2";
pub(super) const ACCESSIBILITY_PROTOCOL: &str = "org.trillionnium.agent-accessibility.v2";
pub(super) const ACCESSIBILITY_IDENTITY_VERSION: &str = "org.trillionnium.agent-accessibility.request-identity.v3";
