// @generated by tools/generate-owner-open-types.py; do not edit.

pub const CONTRACT_SCHEMA: &str = "org.trillionnium.codex-sovereign-direct-tools.v1";
pub const CONTRACT_REVISION: &str = "2026-08-27-r3";
pub const DEFAULT_ANDROID_ABSTRACT_SOCKET: &str = "@trillionnium_direct_agent_host_v1";
pub const DEFAULT_ROOT_LINUX_SOCKET_ALIAS: &str = "/run/trillionnium/direct-agent-host-v1.sock";
pub const DEFAULT_PROFILE_ID: &str = "owner-open";
pub const OWNER_OPEN_REQUEST_TYPE: &str = "RunTurnRequest";
