#!/usr/bin/env python3
"""Generate the Rust constants pinned by the canonical operation binding contract."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "contracts" / "canonical-operation-binding-v1.json"
OUTPUT = ROOT / "src" / "canonical_operation_contract.rs"


def quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def render() -> str:
    raw = CONTRACT.read_bytes()
    contract = json.loads(raw)
    if contract["schema"] != "org.trillionnium.canonical-operation-binding.contract.v1":
        raise SystemExit("unexpected canonical operation binding schema")
    if contract["operation_id"]["model_wire_fields"]:
        raise SystemExit("canonical operation contract exposes reserved model wire fields")
    if contract.get("agents") != {"codex": "agent-codex-v1"}:
        raise SystemExit("canonical operation contract is not Codex-only")
    vectors = contract["vectors"]
    if len(vectors) < 2 or {item["adapter"] for item in vectors} != {
        "system_api",
        "accessibility",
    }:
        raise SystemExit("canonical operation contract lacks both adapter vector sets")
    if any(item.get("agent") != "codex" for item in vectors):
        raise SystemExit("canonical operation contract contains a non-Codex vector")
    digest = hashlib.sha256(raw).hexdigest()
    return f"""// @generated by tools/generate-canonical-operation-binding.py; do not edit.
#[cfg(test)]
pub(super) const CONTRACT_SCHEMA: &str = {quote(contract['schema'])};
#[cfg(test)]
pub(super) const CONTRACT_SHA256: &str = {quote(digest)};
pub(super) const CODEX_REPLAY_NAMESPACE: &str =
    trillionnium_os_types::agent_principal_registry::CODEX_STABLE_PRINCIPAL.replay_namespace;
pub(super) const SYSTEM_API_PROTOCOL: &str = {quote(contract['system_api']['protocol'])};
pub(super) const SYSTEM_API_IDENTITY_VERSION: &str = {quote(contract['system_api']['identity_version'])};
pub(super) const ACCESSIBILITY_PROTOCOL: &str = {quote(contract['accessibility']['protocol'])};
pub(super) const ACCESSIBILITY_IDENTITY_VERSION: &str = {quote(contract['accessibility']['identity_version'])};
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit(f"generated canonical operation constants are stale: {OUTPUT}")
        return
    OUTPUT.write_text(expected)


if __name__ == "__main__":
    main()
