// @generated by tools/generate-agent-principal-registry.py; do not edit.

pub const CONTRACT_SCHEMA: &str = "org.trillionnium.agent-principal-registry.contract.v2";
pub const CONTRACT_SHA256: &str =
    "3e9bfcb04e48062c20bd7407635c1a27086a0de8c2fa5ca73963c946b984095b";
pub const REGISTRY_SCHEMA: &str = "org.trillionnium.agent-principal-registry.v2";
pub const STABLE_PRINCIPAL_SCHEMA: &str = "org.trillionnium.agent-stable-principal.v1";
pub const MATERIALIZATION_STATUS: &str = "hold_same_crate_counterfactual_build_required";
pub const SAME_CRATE_COUNTERFACTUAL_BUILD_REQUIRED: bool = true;
pub const STABLE_PRINCIPAL_CANONICAL_JSON: &str = "{\"schema\":\"org.trillionnium.agent-principal-registry.v2\",\"endpoints\":[{\"symbol\":\"SYSTEM_API\",\"tool_selinux_domain\":\"u:r:trillionnium_agent_system_api_tool:s0\",\"operation_replay_sync_selinux_domain\":\"u:r:trillionnium_agent_system_api_operation_replay_sync:s0\"},{\"symbol\":\"ACCESSIBILITY\",\"tool_selinux_domain\":\"u:r:trillionnium_agent_accessibility_tool:s0\",\"operation_replay_sync_selinux_domain\":\"u:r:trillionnium_agent_accessibility_operation_replay_sync:s0\"}],\"principals\":[{\"schema\":\"org.trillionnium.agent-stable-principal.v1\",\"provider_id\":\"openai-codex\",\"agent_id\":\"agent-codex-direct-v1\",\"replay_namespace\":\"agent-codex-v1\",\"uid\":5901,\"gid\":5901,\"agent_selinux_domain\":\"u:r:trillionnium_codex_agent:s0\",\"runtime_adapter\":\"supervised-codex-cli\"}]}";
pub const STABLE_PRINCIPAL_CANONICAL_SHA256: &str =
    "a9c224116123deb49908beda3ab047fc98d6917cfeb62d60364033858cc57153";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AgentEndpointDescriptor {
    pub symbol: &'static str,
    pub tool_selinux_domain: &'static str,
    pub operation_replay_sync_selinux_domain: &'static str,
}

pub const SYSTEM_API_ENDPOINT: AgentEndpointDescriptor = AgentEndpointDescriptor {
    symbol: "SYSTEM_API",
    tool_selinux_domain: "u:r:trillionnium_agent_system_api_tool:s0",
    operation_replay_sync_selinux_domain: "u:r:trillionnium_agent_system_api_operation_replay_sync:s0",
};
pub const ACCESSIBILITY_ENDPOINT: AgentEndpointDescriptor = AgentEndpointDescriptor {
    symbol: "ACCESSIBILITY",
    tool_selinux_domain: "u:r:trillionnium_agent_accessibility_tool:s0",
    operation_replay_sync_selinux_domain: "u:r:trillionnium_agent_accessibility_operation_replay_sync:s0",
};

pub const PRODUCT_ENDPOINT_ALLOWLIST: &[&AgentEndpointDescriptor] =
    &[&SYSTEM_API_ENDPOINT, &ACCESSIBILITY_ENDPOINT];

pub fn endpoint_from_symbol(symbol: &str) -> Option<&'static AgentEndpointDescriptor> {
    PRODUCT_ENDPOINT_ALLOWLIST
        .iter()
        .copied()
        .find(|endpoint| endpoint.symbol == symbol)
}

pub fn endpoint_from_tool_selinux_domain(
    selinux_domain: &str,
) -> Option<&'static AgentEndpointDescriptor> {
    PRODUCT_ENDPOINT_ALLOWLIST
        .iter()
        .copied()
        .find(|endpoint| endpoint.tool_selinux_domain == selinux_domain)
}

pub fn endpoint_from_operation_replay_sync_selinux_domain(
    selinux_domain: &str,
) -> Option<&'static AgentEndpointDescriptor> {
    PRODUCT_ENDPOINT_ALLOWLIST
        .iter()
        .copied()
        .find(|endpoint| endpoint.operation_replay_sync_selinux_domain == selinux_domain)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AgentStablePrincipal {
    pub provider_id: &'static str,
    pub agent_id: &'static str,
    pub replay_namespace: &'static str,
    pub uid: u32,
    pub gid: u32,
    pub agent_selinux_domain: &'static str,
    pub runtime_adapter: &'static str,
}

impl AgentStablePrincipal {
    /// Match only stable, kernel-authenticated registration fields. The
    /// executable/launcher digest and dynamic readiness state are deliberately
    /// outside this stable-principal projection and remain separate gates.
    pub fn matches_registration_fields(&self, registration: &crate::AgentRegistration) -> bool {
        registration.agent_id == self.agent_id
            && registration.adapter == self.runtime_adapter
            && registration.peer_uid == self.uid
            && registration.peer_gid == self.gid
            && registration.selinux_domain == self.agent_selinux_domain
    }
}

pub const CODEX_STABLE_PRINCIPAL: AgentStablePrincipal = AgentStablePrincipal {
    provider_id: "openai-codex",
    agent_id: "agent-codex-direct-v1",
    replay_namespace: "agent-codex-v1",
    uid: 5901,
    gid: 5901,
    agent_selinux_domain: "u:r:trillionnium_codex_agent:s0",
    runtime_adapter: "supervised-codex-cli",
};

pub const PRODUCT_ALLOWLIST: &[&AgentStablePrincipal] = &[&CODEX_STABLE_PRINCIPAL];

pub fn from_provider_id(provider_id: &str) -> Option<&'static AgentStablePrincipal> {
    PRODUCT_ALLOWLIST
        .iter()
        .copied()
        .find(|principal| principal.provider_id == provider_id)
}

pub fn from_agent_id(agent_id: &str) -> Option<&'static AgentStablePrincipal> {
    PRODUCT_ALLOWLIST
        .iter()
        .copied()
        .find(|principal| principal.agent_id == agent_id)
}

pub fn from_replay_namespace(replay_namespace: &str) -> Option<&'static AgentStablePrincipal> {
    PRODUCT_ALLOWLIST
        .iter()
        .copied()
        .find(|principal| principal.replay_namespace == replay_namespace)
}

pub fn from_provider_agent_pair(
    provider_id: &str,
    agent_id: &str,
) -> Option<&'static AgentStablePrincipal> {
    from_provider_id(provider_id).filter(|principal| principal.agent_id == agent_id)
}

pub fn from_uid_gid(uid: u32, gid: u32) -> Option<&'static AgentStablePrincipal> {
    PRODUCT_ALLOWLIST
        .iter()
        .copied()
        .find(|principal| principal.uid == uid && principal.gid == gid)
}

pub fn from_registration_fields(
    registration: &crate::AgentRegistration,
) -> Option<&'static AgentStablePrincipal> {
    from_agent_id(&registration.agent_id)
        .filter(|principal| principal.matches_registration_fields(registration))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{AgentHealth, AgentNetworkPolicy, AgentRegistration};

    fn registration(principal: &AgentStablePrincipal) -> AgentRegistration {
        AgentRegistration {
            api_version: crate::AGENT_API_VERSION.to_string(),
            agent_id: principal.agent_id.to_string(),
            adapter: principal.runtime_adapter.to_string(),
            adapter_version: "stable-principal-test".to_string(),
            identity_key_sha256: "f".repeat(64),
            peer_uid: principal.uid,
            peer_gid: principal.gid,
            selinux_domain: principal.agent_selinux_domain.to_string(),
            network_policy: AgentNetworkPolicy::Deny,
            enabled: false,
            health: AgentHealth::Offline,
            registered_at_unix_ms: 1,
            updated_at_unix_ms: 1,
        }
    }

    #[test]
    fn generated_contract_and_canonical_principal_hashes_are_exact() {
        assert_eq!(
            crate::sha256_bytes(include_bytes!(
                "../contracts/agent-principal-registry-v2.json"
            )),
            CONTRACT_SHA256
        );
        assert_eq!(
            crate::sha256_bytes(STABLE_PRINCIPAL_CANONICAL_JSON.as_bytes()),
            STABLE_PRINCIPAL_CANONICAL_SHA256
        );
        assert_eq!(
            STABLE_PRINCIPAL_CANONICAL_SHA256,
            "a9c224116123deb49908beda3ab047fc98d6917cfeb62d60364033858cc57153"
        );
        assert_eq!(
            MATERIALIZATION_STATUS,
            "hold_same_crate_counterfactual_build_required"
        );
        const {
            assert!(SAME_CRATE_COUNTERFACTUAL_BUILD_REQUIRED);
        }
    }

    #[test]
    fn generated_principals_match_the_canonical_registry() {
        let registry: serde_json::Value = serde_json::from_str(STABLE_PRINCIPAL_CANONICAL_JSON)
            .expect("generated stable principal JSON");
        assert_eq!(registry["schema"], REGISTRY_SCHEMA);
        let endpoints = registry["endpoints"]
            .as_array()
            .expect("generated endpoint array");
        assert_eq!(endpoints.len(), PRODUCT_ENDPOINT_ALLOWLIST.len());
        for (actual, expected) in endpoints.iter().zip(PRODUCT_ENDPOINT_ALLOWLIST) {
            let actual = actual.as_object().expect("generated endpoint object");
            assert_eq!(actual.len(), 3);
            assert_eq!(actual["symbol"], expected.symbol);
            assert_eq!(actual["tool_selinux_domain"], expected.tool_selinux_domain);
            assert_eq!(
                actual["operation_replay_sync_selinux_domain"],
                expected.operation_replay_sync_selinux_domain
            );
        }
        let principals = registry["principals"]
            .as_array()
            .expect("generated stable principal array");
        assert_eq!(principals.len(), PRODUCT_ALLOWLIST.len());
        for (actual, expected) in principals.iter().zip(PRODUCT_ALLOWLIST) {
            let actual = actual
                .as_object()
                .expect("generated stable principal object");
            assert_eq!(actual.len(), 8);
            assert_eq!(actual["schema"], STABLE_PRINCIPAL_SCHEMA);
            assert_eq!(actual["provider_id"], expected.provider_id);
            assert_eq!(actual["agent_id"], expected.agent_id);
            assert_eq!(actual["replay_namespace"], expected.replay_namespace);
            assert_eq!(actual["uid"], expected.uid);
            assert_eq!(actual["gid"], expected.gid);
            assert_eq!(
                actual["agent_selinux_domain"],
                expected.agent_selinux_domain
            );
            assert_eq!(actual["runtime_adapter"], expected.runtime_adapter);
            assert!(actual.get("identity_key_sha256").is_none());
        }
    }

    #[test]
    fn stable_principal_matches_v1_descriptor_non_identity_fields() {
        let stable = CODEX_STABLE_PRINCIPAL;
        let exact = crate::agent_descriptor_registry::CODEX;
        assert_eq!(stable.provider_id, exact.provider_id);
        assert_eq!(stable.agent_id, exact.agent_id);
        assert_eq!(stable.replay_namespace, exact.replay_namespace);
        assert_eq!(stable.uid, exact.uid);
        assert_eq!(stable.gid, exact.gid);
        assert_eq!(stable.agent_selinux_domain, exact.agent_selinux_domain);
        assert_eq!(stable.runtime_adapter, exact.runtime_adapter);
        assert_eq!(
            SYSTEM_API_ENDPOINT.tool_selinux_domain,
            crate::agent_descriptor_registry::SYSTEM_API_ENDPOINT.tool_selinux_domain
        );
        assert_eq!(
            SYSTEM_API_ENDPOINT.operation_replay_sync_selinux_domain,
            crate::agent_descriptor_registry::SYSTEM_API_ENDPOINT
                .operation_replay_sync_selinux_domain
        );
        assert_eq!(
            ACCESSIBILITY_ENDPOINT.tool_selinux_domain,
            crate::agent_descriptor_registry::ACCESSIBILITY_ENDPOINT.tool_selinux_domain
        );
        assert_eq!(
            ACCESSIBILITY_ENDPOINT.operation_replay_sync_selinux_domain,
            crate::agent_descriptor_registry::ACCESSIBILITY_ENDPOINT
                .operation_replay_sync_selinux_domain
        );
    }

    #[test]
    fn generated_endpoint_domains_are_closed_disjoint_and_lookup_bound() {
        assert_eq!(PRODUCT_ENDPOINT_ALLOWLIST.len(), 2);
        assert_eq!(
            endpoint_from_symbol("SYSTEM_API"),
            Some(&SYSTEM_API_ENDPOINT)
        );
        assert_eq!(
            endpoint_from_tool_selinux_domain(ACCESSIBILITY_ENDPOINT.tool_selinux_domain),
            Some(&ACCESSIBILITY_ENDPOINT)
        );
        assert_eq!(
            endpoint_from_operation_replay_sync_selinux_domain(
                SYSTEM_API_ENDPOINT.operation_replay_sync_selinux_domain
            ),
            Some(&SYSTEM_API_ENDPOINT)
        );
        assert_ne!(
            SYSTEM_API_ENDPOINT.tool_selinux_domain,
            SYSTEM_API_ENDPOINT.operation_replay_sync_selinux_domain
        );
        assert_ne!(
            SYSTEM_API_ENDPOINT.tool_selinux_domain,
            ACCESSIBILITY_ENDPOINT.tool_selinux_domain
        );
        assert_eq!(endpoint_from_symbol("MODEL_AUTHORED"), None);
    }

    #[test]
    fn stable_principal_lookups_are_closed_and_pair_bound() {
        assert_eq!(PRODUCT_ALLOWLIST, &[&CODEX_STABLE_PRINCIPAL]);
        assert_eq!(
            from_provider_id(CODEX_STABLE_PRINCIPAL.provider_id),
            Some(&CODEX_STABLE_PRINCIPAL)
        );
        assert_eq!(
            from_agent_id(CODEX_STABLE_PRINCIPAL.agent_id),
            Some(&CODEX_STABLE_PRINCIPAL)
        );
        assert_eq!(
            from_replay_namespace(CODEX_STABLE_PRINCIPAL.replay_namespace),
            Some(&CODEX_STABLE_PRINCIPAL)
        );
        assert_eq!(
            from_uid_gid(CODEX_STABLE_PRINCIPAL.uid, CODEX_STABLE_PRINCIPAL.gid),
            Some(&CODEX_STABLE_PRINCIPAL)
        );
        assert_eq!(
            from_provider_agent_pair(CODEX_STABLE_PRINCIPAL.provider_id, "agent-retired-v1"),
            None
        );
        assert_eq!(from_provider_id("model-authored-provider"), None);
    }

    #[test]
    fn registration_lookup_ignores_rotating_digest_and_dynamic_state_only() {
        let mut registration = registration(&CODEX_STABLE_PRINCIPAL);
        assert_eq!(
            from_registration_fields(&registration),
            Some(&CODEX_STABLE_PRINCIPAL)
        );
        registration.identity_key_sha256 = "a".repeat(64);
        registration.enabled = true;
        registration.health = AgentHealth::Ready;
        assert_eq!(
            from_registration_fields(&registration),
            Some(&CODEX_STABLE_PRINCIPAL)
        );
        registration.peer_uid += 1;
        assert_eq!(from_registration_fields(&registration), None);
    }

    #[test]
    fn canonical_operation_namespaces_match_the_stable_principals() {
        let operation: serde_json::Value = serde_json::from_slice(include_bytes!(
            "../../trillionnium-agent-direct-tools/contracts/canonical-operation-binding-v1.json"
        ))
        .expect("canonical operation contract");
        assert_eq!(
            operation["agents"]["codex"],
            CODEX_STABLE_PRINCIPAL.replay_namespace
        );
    }
}
