// @generated by tools/generate-agent-descriptor-registry.py; do not edit.

pub const CONTRACT_SCHEMA: &str = "org.trillionnium.agent-descriptor-registry.contract.v1";
pub const CONTRACT_SHA256: &str =
    "5ecd89d3c9fedbbeb0ac1de32fba2b5e5e5d248048ddc9a9e0359a0a01903119";
pub const REGISTRY_SCHEMA: &str = "org.trillionnium.agent-descriptor-registry.v1";
pub const DESCRIPTOR_SCHEMA: &str = "org.trillionnium.agent-descriptor.v1";
pub const CANONICAL_REGISTRY_JSON: &str = "{\"schema\":\"org.trillionnium.agent-descriptor-registry.v1\",\"descriptors\":[{\"schema\":\"org.trillionnium.agent-descriptor.v1\",\"provider_id\":\"openai-codex\",\"agent_id\":\"agent-codex-direct-v1\",\"identity_key_sha256\":\"edcf9d31da8b48d29575115a7242691c1337174edf42573b7274b652a4cd571c\",\"replay_namespace\":\"agent-codex-v1\",\"uid\":5901,\"gid\":5901,\"agent_selinux_domain\":\"u:r:trillionnium_codex_agent:s0\",\"runtime_adapter\":\"supervised-codex-cli\"}]}";
pub const CANONICAL_REGISTRY_SHA256: &str =
    "bc6c64abbb893e6e75ed708f87cf864e6c8f7503381371dc394409bddc4009c2";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AgentEndpointDescriptor {
    pub symbol: &'static str,
    pub tool_selinux_domain: &'static str,
    pub operation_replay_sync_selinux_domain: &'static str,
}

pub const SYSTEM_API_ENDPOINT: AgentEndpointDescriptor = AgentEndpointDescriptor {
    symbol: "SYSTEM_API",
    tool_selinux_domain: "u:r:trillionnium_agent_system_api_tool:s0",
    operation_replay_sync_selinux_domain: "u:r:trillionnium_agent_system_api_operation_replay_sync:s0",
};
pub const ACCESSIBILITY_ENDPOINT: AgentEndpointDescriptor = AgentEndpointDescriptor {
    symbol: "ACCESSIBILITY",
    tool_selinux_domain: "u:r:trillionnium_agent_accessibility_tool:s0",
    operation_replay_sync_selinux_domain: "u:r:trillionnium_agent_accessibility_operation_replay_sync:s0",
};

pub const PRODUCT_ENDPOINT_ALLOWLIST: &[&AgentEndpointDescriptor] =
    &[&SYSTEM_API_ENDPOINT, &ACCESSIBILITY_ENDPOINT];

pub fn endpoint_from_symbol(symbol: &str) -> Option<&'static AgentEndpointDescriptor> {
    PRODUCT_ENDPOINT_ALLOWLIST
        .iter()
        .copied()
        .find(|endpoint| endpoint.symbol == symbol)
}

pub fn endpoint_from_tool_selinux_domain(
    selinux_domain: &str,
) -> Option<&'static AgentEndpointDescriptor> {
    PRODUCT_ENDPOINT_ALLOWLIST
        .iter()
        .copied()
        .find(|endpoint| endpoint.tool_selinux_domain == selinux_domain)
}

pub fn endpoint_from_operation_replay_sync_selinux_domain(
    selinux_domain: &str,
) -> Option<&'static AgentEndpointDescriptor> {
    PRODUCT_ENDPOINT_ALLOWLIST
        .iter()
        .copied()
        .find(|endpoint| endpoint.operation_replay_sync_selinux_domain == selinux_domain)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AgentDescriptor {
    pub provider_id: &'static str,
    pub agent_id: &'static str,
    pub identity_key_sha256: &'static str,
    pub replay_namespace: &'static str,
    pub uid: u32,
    pub gid: u32,
    pub agent_selinux_domain: &'static str,
    pub runtime_adapter: &'static str,
}

impl AgentDescriptor {
    pub fn matches_registration(&self, registration: &crate::AgentRegistration) -> bool {
        registration.agent_id == self.agent_id
            && registration.adapter == self.runtime_adapter
            && registration.identity_key_sha256 == self.identity_key_sha256
            && registration.peer_uid == self.uid
            && registration.peer_gid == self.gid
            && registration.selinux_domain == self.agent_selinux_domain
    }
}

pub const CODEX: AgentDescriptor = AgentDescriptor {
    provider_id: "openai-codex",
    agent_id: "agent-codex-direct-v1",
    identity_key_sha256: "edcf9d31da8b48d29575115a7242691c1337174edf42573b7274b652a4cd571c",
    replay_namespace: "agent-codex-v1",
    uid: 5901,
    gid: 5901,
    agent_selinux_domain: "u:r:trillionnium_codex_agent:s0",
    runtime_adapter: "supervised-codex-cli",
};

pub const PRODUCT_ALLOWLIST: &[&AgentDescriptor] = &[&CODEX];

pub fn from_provider_id(provider_id: &str) -> Option<&'static AgentDescriptor> {
    PRODUCT_ALLOWLIST
        .iter()
        .copied()
        .find(|descriptor| descriptor.provider_id == provider_id)
}

pub fn from_agent_id(agent_id: &str) -> Option<&'static AgentDescriptor> {
    PRODUCT_ALLOWLIST
        .iter()
        .copied()
        .find(|descriptor| descriptor.agent_id == agent_id)
}

pub fn from_replay_namespace(replay_namespace: &str) -> Option<&'static AgentDescriptor> {
    PRODUCT_ALLOWLIST
        .iter()
        .copied()
        .find(|descriptor| descriptor.replay_namespace == replay_namespace)
}

pub fn from_provider_agent_pair(
    provider_id: &str,
    agent_id: &str,
) -> Option<&'static AgentDescriptor> {
    from_provider_id(provider_id).filter(|descriptor| descriptor.agent_id == agent_id)
}

pub fn from_uid_gid(uid: u32, gid: u32) -> Option<&'static AgentDescriptor> {
    PRODUCT_ALLOWLIST
        .iter()
        .copied()
        .find(|descriptor| descriptor.uid == uid && descriptor.gid == gid)
}

pub fn from_registration(
    registration: &crate::AgentRegistration,
) -> Option<&'static AgentDescriptor> {
    from_agent_id(&registration.agent_id)
        .filter(|descriptor| descriptor.matches_registration(registration))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_contract_and_canonical_registry_hashes_are_exact() {
        assert_eq!(
            crate::sha256_bytes(include_bytes!(
                "../contracts/agent-descriptor-registry-v1.json"
            )),
            CONTRACT_SHA256
        );
        assert_eq!(
            crate::sha256_bytes(CANONICAL_REGISTRY_JSON.as_bytes()),
            CANONICAL_REGISTRY_SHA256
        );
        assert_eq!(
            CANONICAL_REGISTRY_SHA256,
            "bc6c64abbb893e6e75ed708f87cf864e6c8f7503381371dc394409bddc4009c2"
        );
    }

    #[test]
    fn generated_descriptors_match_the_canonical_registry() {
        let registry: serde_json::Value =
            serde_json::from_str(CANONICAL_REGISTRY_JSON).expect("generated registry JSON");
        assert_eq!(registry["schema"], REGISTRY_SCHEMA);
        let descriptors = registry["descriptors"]
            .as_array()
            .expect("generated descriptor array");
        assert_eq!(descriptors.len(), PRODUCT_ALLOWLIST.len());
        for (actual, expected) in descriptors.iter().zip(PRODUCT_ALLOWLIST) {
            let actual = actual.as_object().expect("generated descriptor object");
            assert_eq!(actual.len(), 9);
            assert_eq!(actual["schema"], DESCRIPTOR_SCHEMA);
            assert_eq!(actual["provider_id"], expected.provider_id);
            assert_eq!(actual["agent_id"], expected.agent_id);
            assert_eq!(actual["identity_key_sha256"], expected.identity_key_sha256);
            assert_eq!(actual["replay_namespace"], expected.replay_namespace);
            assert_eq!(actual["uid"], expected.uid);
            assert_eq!(actual["gid"], expected.gid);
            assert_eq!(
                actual["agent_selinux_domain"],
                expected.agent_selinux_domain
            );
            assert_eq!(actual["runtime_adapter"], expected.runtime_adapter);
        }
    }

    #[test]
    fn generated_endpoint_domains_are_closed_disjoint_and_lookup_bound() {
        assert_eq!(PRODUCT_ENDPOINT_ALLOWLIST.len(), 2);
        assert_eq!(
            endpoint_from_symbol("SYSTEM_API"),
            Some(&SYSTEM_API_ENDPOINT)
        );
        assert_eq!(
            endpoint_from_tool_selinux_domain(ACCESSIBILITY_ENDPOINT.tool_selinux_domain),
            Some(&ACCESSIBILITY_ENDPOINT)
        );
        assert_eq!(
            endpoint_from_operation_replay_sync_selinux_domain(
                SYSTEM_API_ENDPOINT.operation_replay_sync_selinux_domain
            ),
            Some(&SYSTEM_API_ENDPOINT)
        );
        assert_ne!(
            SYSTEM_API_ENDPOINT.tool_selinux_domain,
            SYSTEM_API_ENDPOINT.operation_replay_sync_selinux_domain
        );
        assert_ne!(
            SYSTEM_API_ENDPOINT.tool_selinux_domain,
            ACCESSIBILITY_ENDPOINT.tool_selinux_domain
        );
        assert_eq!(endpoint_from_symbol("MODEL_AUTHORED"), None);
    }

    #[test]
    fn canonical_operation_namespaces_match_the_generated_descriptors() {
        let operation: serde_json::Value = serde_json::from_slice(include_bytes!(
            "../../trillionnium-agent-direct-tools/contracts/canonical-operation-binding-v1.json"
        ))
        .expect("canonical operation contract");
        assert_eq!(operation["agents"]["codex"], CODEX.replay_namespace);
    }

    #[test]
    fn product_identity_lookups_are_closed_and_pair_bound() {
        assert_eq!(PRODUCT_ALLOWLIST, &[&CODEX]);
        assert_eq!(from_provider_id(CODEX.provider_id), Some(&CODEX));
        assert_eq!(from_agent_id(CODEX.agent_id), Some(&CODEX));
        assert_eq!(from_replay_namespace(CODEX.replay_namespace), Some(&CODEX));
        assert_eq!(from_uid_gid(CODEX.uid, CODEX.gid), Some(&CODEX));
        assert_eq!(
            from_provider_agent_pair(CODEX.provider_id, "agent-retired-v1"),
            None
        );
        assert_eq!(from_provider_id("model-authored-provider"), None);
    }
}
