// @generated by tools/generate-capability-lease-root-registration.py; do not edit.

use std::error::Error;
use std::fmt;

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::agent_principal_registry;
use crate::capability_lease_agent_binding::{
    CAPABILITY_LEASE_OPEN_URI_ACTION_KIND, resolve_system_api_open_uri_agent_binding,
};
use crate::direct_operation::{DirectOperationAdapter, DirectOperationBindingInbox};
use crate::sha256_bytes;

pub const CONTRACT_SCHEMA: &str = "org.trillionnium.capabilitylease.root-registration.contract.v1";
pub const CONTRACT_SHA256: &str =
    "7e71b2fd71b6dbd87ec83b5b649dba743d63846cdf1da51c42b5977959e6815a";
pub const TASK_REGISTRATION_SCHEMA: &str =
    "org.trillionnium.capabilitylease.root-task-registration.v1";
pub const SOURCE_STATUS: &str = "source_only_no_transport_no_runtime_no_effect_authority_v1";
pub const REGISTRATION_BINDING_DOMAIN: &str = "trillionnium.capability-lease-root-registration.v1";
pub const TASK_CONTEXT_KIND: &str = "TASK_CONTEXT";
pub const ADAPTER_ID: &str = "system_api";
pub const ACTION_ID: &str = "open_uri";
pub const SUBJECT_USER_ID: u64 = 0;
pub const OPAQUE_TASK_CONTEXT_TOKEN_PREFIX: &str = "task-context-";
pub const TRANSPORT_AVAILABLE: bool = false;
pub const RUNTIME_CONSUMER_AVAILABLE: bool = false;
pub const CONFERS_EFFECT_AUTHORITY: bool = false;

pub const BINDING_FIELDS: &[&str] = &[
    "domain",
    "kind",
    "peer",
    "boot_id_sha256",
    "publisher_epoch",
    "root_journal_genesis_sha256",
    "epoch_proof_sha256",
    "publisher_sequence",
    "adapter",
    "action",
    "subject_user",
    "opaque_token_sha256",
    "request_id",
    "canonical_request_sha256",
    "workflow_id",
    "task_id",
    "authenticated_task_binding_sha256",
    "root_direct_binding_sha256",
];
pub const PAYLOAD_FIELDS: &[&str] = &[
    "schema",
    "provider_id",
    "agent_id",
    "replay_namespace",
    "boot_id_sha256",
    "publisher_epoch",
    "publisher_sequence",
    "root_journal_genesis_sha256",
    "epoch_proof_sha256",
    "opaque_task_context_token",
    "prepare_request_id",
    "prepare_canonical_request_sha256",
    "workflow_id",
    "task_id",
    "authenticated_task_binding_sha256",
    "root_direct_binding_sha256",
    "registration_binding_sha256",
];

pub const GOLDEN_OPAQUE_TOKEN_SHA256: &str =
    "31839495296e57aac36136f5ac3a8265b2661352e7502f01d20743331ab86a89";
pub const GOLDEN_REGISTRATION_BINDING_SHA256: &str =
    "5c67053c1e83212a6ab7fb189789c421c7544353da4787d5cf459d35ec43b956";

pub type CapabilityLeaseRootRegistrationResult<T> = Result<T, CapabilityLeaseRootRegistrationError>;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CapabilityLeaseRootRegistrationError(&'static str);

impl CapabilityLeaseRootRegistrationError {
    #[must_use]
    pub const fn code(self) -> &'static str {
        self.0
    }
}

impl fmt::Display for CapabilityLeaseRootRegistrationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.0)
    }
}

impl Error for CapabilityLeaseRootRegistrationError {}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct CapabilityLeaseRootPublisherEvidenceV1 {
    pub boot_id_sha256: String,
    pub publisher_epoch: String,
    pub publisher_sequence: u64,
    pub root_journal_genesis_sha256: String,
    pub epoch_proof_sha256: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct CapabilityLeaseRootTaskContextV1 {
    pub opaque_task_context_token: String,
    pub prepare_request_id: String,
    pub prepare_canonical_request_sha256: String,
    pub workflow_id: String,
    pub task_id: String,
    pub authenticated_task_binding_sha256: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct CapabilityLeaseRootTaskRegistrationV1 {
    pub schema: String,
    pub provider_id: String,
    pub agent_id: String,
    pub replay_namespace: String,
    pub boot_id_sha256: String,
    pub publisher_epoch: String,
    pub publisher_sequence: u64,
    pub root_journal_genesis_sha256: String,
    pub epoch_proof_sha256: String,
    pub opaque_task_context_token: String,
    pub prepare_request_id: String,
    pub prepare_canonical_request_sha256: String,
    pub workflow_id: String,
    pub task_id: String,
    pub authenticated_task_binding_sha256: String,
    pub root_direct_binding_sha256: String,
    pub registration_binding_sha256: String,
}

impl CapabilityLeaseRootTaskRegistrationV1 {
    pub fn derive(
        provider_id: String,
        agent_id: String,
        replay_namespace: String,
        publisher: CapabilityLeaseRootPublisherEvidenceV1,
        task: CapabilityLeaseRootTaskContextV1,
        root_direct_binding_sha256: String,
    ) -> CapabilityLeaseRootRegistrationResult<Self> {
        let mut value = Self {
            schema: TASK_REGISTRATION_SCHEMA.to_string(),
            provider_id,
            agent_id,
            replay_namespace,
            boot_id_sha256: publisher.boot_id_sha256,
            publisher_epoch: publisher.publisher_epoch,
            publisher_sequence: publisher.publisher_sequence,
            root_journal_genesis_sha256: publisher.root_journal_genesis_sha256,
            epoch_proof_sha256: publisher.epoch_proof_sha256,
            opaque_task_context_token: task.opaque_task_context_token,
            prepare_request_id: task.prepare_request_id,
            prepare_canonical_request_sha256: task.prepare_canonical_request_sha256,
            workflow_id: task.workflow_id,
            task_id: task.task_id,
            authenticated_task_binding_sha256: task.authenticated_task_binding_sha256,
            root_direct_binding_sha256,
            registration_binding_sha256: String::new(),
        };
        value.validate_preimage()?;
        value.registration_binding_sha256 = value.expected_binding_sha256()?;
        value.validate()?;
        Ok(value)
    }

    pub fn validate(&self) -> CapabilityLeaseRootRegistrationResult<()> {
        self.validate_preimage()?;
        if !valid_nonzero_lower_hex(&self.registration_binding_sha256, 64)
            || self.expected_binding_sha256()? != self.registration_binding_sha256
        {
            return Err(denied("capability_lease_root_registration_binding_denied"));
        }
        Ok(())
    }

    pub fn validate_for_inbox(
        &self,
        inbox: &DirectOperationBindingInbox,
    ) -> CapabilityLeaseRootRegistrationResult<()> {
        self.validate()?;
        inbox
            .validate()
            .map_err(|_| denied("capability_lease_root_registration_inbox_denied"))?;
        if self.provider_id != inbox.binding.stable_seed.provider_id
            || self.agent_id != inbox.binding.stable_seed.agent_id
            || self.task_id != inbox.binding.stable_seed.task_id
            || self.root_direct_binding_sha256 != inbox.binding_sha256
            || self.workflow_id_sha256() != inbox.binding.workflow_id_sha256
        {
            return Err(denied("capability_lease_root_registration_inbox_denied"));
        }
        Ok(())
    }

    pub fn binding_sha256(&self) -> CapabilityLeaseRootRegistrationResult<String> {
        self.validate()?;
        Ok(self.registration_binding_sha256.clone())
    }

    pub fn opaque_token_sha256(&self) -> CapabilityLeaseRootRegistrationResult<String> {
        if !valid_task_context_token(&self.opaque_task_context_token) {
            return Err(denied("capability_lease_root_registration_task_denied"));
        }
        Ok(sha256_bytes(self.opaque_task_context_token.as_bytes()))
    }

    fn workflow_id_sha256(&self) -> String {
        sha256_bytes(self.workflow_id.as_bytes())
    }

    fn validate_preimage(&self) -> CapabilityLeaseRootRegistrationResult<()> {
        if self.schema != TASK_REGISTRATION_SCHEMA {
            return Err(denied("capability_lease_root_registration_schema_denied"));
        }
        let principal =
            agent_principal_registry::from_provider_agent_pair(&self.provider_id, &self.agent_id)
                .ok_or_else(|| denied("capability_lease_root_registration_descriptor_denied"))?;
        if self.replay_namespace != principal.replay_namespace {
            return Err(denied(
                "capability_lease_root_registration_descriptor_denied",
            ));
        }
        if !valid_nonzero_lower_hex(&self.boot_id_sha256, 64)
            || !valid_nonzero_lower_hex(&self.publisher_epoch, 32)
            || self.publisher_sequence == 0
            || self.publisher_sequence > i64::MAX as u64
            || !valid_nonzero_lower_hex(&self.root_journal_genesis_sha256, 64)
            || !valid_nonzero_lower_hex(&self.epoch_proof_sha256, 64)
        {
            return Err(denied(
                "capability_lease_root_registration_publisher_denied",
            ));
        }
        if !valid_task_context_token(&self.opaque_task_context_token)
            || !valid_request_id(&self.prepare_request_id)
            || !valid_nonzero_lower_hex(&self.prepare_canonical_request_sha256, 64)
            || !valid_workflow_id(&self.workflow_id)
            || !valid_task_id(&self.task_id)
            || !valid_nonzero_lower_hex(&self.authenticated_task_binding_sha256, 64)
            || !valid_nonzero_lower_hex(&self.root_direct_binding_sha256, 64)
        {
            return Err(denied("capability_lease_root_registration_task_denied"));
        }
        Ok(())
    }

    fn expected_binding_sha256(&self) -> CapabilityLeaseRootRegistrationResult<String> {
        self.validate_preimage()?;
        let mut hasher = Sha256::new();
        hash_string_field(&mut hasher, "domain", REGISTRATION_BINDING_DOMAIN)?;
        hash_string_field(&mut hasher, "kind", TASK_CONTEXT_KIND)?;
        hash_string_field(&mut hasher, "peer", &self.replay_namespace)?;
        hash_string_field(&mut hasher, "boot_id_sha256", &self.boot_id_sha256)?;
        hash_string_field(&mut hasher, "publisher_epoch", &self.publisher_epoch)?;
        hash_string_field(
            &mut hasher,
            "root_journal_genesis_sha256",
            &self.root_journal_genesis_sha256,
        )?;
        hash_string_field(&mut hasher, "epoch_proof_sha256", &self.epoch_proof_sha256)?;
        hash_u64_field(&mut hasher, "publisher_sequence", self.publisher_sequence)?;
        hash_string_field(&mut hasher, "adapter", ADAPTER_ID)?;
        hash_string_field(&mut hasher, "action", ACTION_ID)?;
        hash_u64_field(&mut hasher, "subject_user", SUBJECT_USER_ID)?;
        hash_string_field(
            &mut hasher,
            "opaque_token_sha256",
            &self.opaque_token_sha256()?,
        )?;
        hash_string_field(&mut hasher, "request_id", &self.prepare_request_id)?;
        hash_string_field(
            &mut hasher,
            "canonical_request_sha256",
            &self.prepare_canonical_request_sha256,
        )?;
        hash_string_field(&mut hasher, "workflow_id", &self.workflow_id)?;
        hash_string_field(&mut hasher, "task_id", &self.task_id)?;
        hash_string_field(
            &mut hasher,
            "authenticated_task_binding_sha256",
            &self.authenticated_task_binding_sha256,
        )?;
        hash_string_field(
            &mut hasher,
            "root_direct_binding_sha256",
            &self.root_direct_binding_sha256,
        )?;
        Ok(lower_hex(&hasher.finalize()))
    }
}

pub fn derive_system_api_open_uri_root_task_registration(
    inbox: &DirectOperationBindingInbox,
    publisher: CapabilityLeaseRootPublisherEvidenceV1,
    task: CapabilityLeaseRootTaskContextV1,
) -> CapabilityLeaseRootRegistrationResult<CapabilityLeaseRootTaskRegistrationV1> {
    let agent = resolve_system_api_open_uri_agent_binding(
        inbox,
        &task.workflow_id,
        &task.task_id,
        &inbox.binding.stable_seed.provider_id,
        DirectOperationAdapter::SystemApi,
        CAPABILITY_LEASE_OPEN_URI_ACTION_KIND,
    )
    .map_err(|_| denied("capability_lease_root_registration_inbox_denied"))?;
    let principal =
        agent_principal_registry::from_provider_agent_pair(&agent.provider_id, &agent.agent_id)
            .ok_or_else(|| denied("capability_lease_root_registration_descriptor_denied"))?;
    let registration = CapabilityLeaseRootTaskRegistrationV1::derive(
        agent.provider_id,
        agent.agent_id,
        principal.replay_namespace.to_string(),
        publisher,
        task,
        inbox.binding_sha256.clone(),
    )?;
    registration.validate_for_inbox(inbox)?;
    Ok(registration)
}

fn hash_string_field(
    hasher: &mut Sha256,
    name: &str,
    value: &str,
) -> CapabilityLeaseRootRegistrationResult<()> {
    hash_bytes_field(hasher, name, value.as_bytes())
}

fn hash_u64_field(
    hasher: &mut Sha256,
    name: &str,
    value: u64,
) -> CapabilityLeaseRootRegistrationResult<()> {
    hash_bytes_field(hasher, name, &value.to_be_bytes())
}

fn hash_bytes_field(
    hasher: &mut Sha256,
    name: &str,
    value: &[u8],
) -> CapabilityLeaseRootRegistrationResult<()> {
    let name_length = u32::try_from(name.len())
        .map_err(|_| denied("capability_lease_root_registration_binding_denied"))?;
    let value_length = u32::try_from(value.len())
        .map_err(|_| denied("capability_lease_root_registration_binding_denied"))?;
    hasher.update(name_length.to_be_bytes());
    hasher.update(name.as_bytes());
    hasher.update(value_length.to_be_bytes());
    hasher.update(value);
    Ok(())
}

fn valid_nonzero_lower_hex(value: &str, width: usize) -> bool {
    value.len() == width
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
        && value.bytes().any(|byte| byte != b'0')
}

fn valid_request_id(value: &str) -> bool {
    !value.is_empty() && value.len() <= 128 && value.bytes().all(valid_ascii_identifier_byte)
}

fn valid_workflow_id(value: &str) -> bool {
    value
        .strip_prefix("req-")
        .is_some_and(|suffix| valid_lower_hex(suffix, 32))
}

fn valid_task_id(value: &str) -> bool {
    let mut bytes = value.bytes();
    bytes
        .next()
        .is_some_and(|byte| byte.is_ascii_alphanumeric())
        && value.len() <= 128
        && bytes.all(valid_ascii_identifier_byte)
}

fn valid_task_context_token(value: &str) -> bool {
    value
        .strip_prefix(OPAQUE_TASK_CONTEXT_TOKEN_PREFIX)
        .is_some_and(|suffix| valid_nonzero_lower_hex(suffix, 64))
}

fn valid_lower_hex(value: &str, width: usize) -> bool {
    value.len() == width
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn valid_ascii_identifier_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b':' | b'-')
}

fn lower_hex(value: &[u8]) -> String {
    const ALPHABET: &[u8; 16] = b"0123456789abcdef";
    let mut output = String::with_capacity(value.len() * 2);
    for byte in value {
        output.push(ALPHABET[(byte >> 4) as usize] as char);
        output.push(ALPHABET[(byte & 0x0f) as usize] as char);
    }
    output
}

const fn denied(code: &'static str) -> CapabilityLeaseRootRegistrationError {
    CapabilityLeaseRootRegistrationError(code)
}

#[cfg(test)]
#[allow(clippy::assertions_on_constants)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;
    use crate::agent_descriptor_registry::{AgentDescriptor, CODEX};
    use crate::direct_operation::{
        BINDING_INBOX_SCHEMA, BINDING_SCHEMA, DirectOperationBinding,
        DirectOperationProviderAttempt, DirectOperationStableSeed, STABLE_SEED_SCHEMA,
    };

    const GOLDEN_BOOT: &str = "1111111111111111111111111111111111111111111111111111111111111111";
    const GOLDEN_EPOCH: &str = "88888888888888888888888888888888";
    const GOLDEN_ROOT_GENESIS: &str =
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    const GOLDEN_EPOCH_PROOF: &str =
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
    const GOLDEN_TASK_TOKEN: &str =
        "task-context-2222222222222222222222222222222222222222222222222222222222222222";
    const GOLDEN_PREPARE_REQUEST: &str = "prepare-token-registry";
    const GOLDEN_PREPARE_CANONICAL: &str =
        "9999999999999999999999999999999999999999999999999999999999999999";
    const GOLDEN_WORKFLOW: &str = "req-44444444444444444444444444444444";
    const GOLDEN_TASK: &str = "task.token-registry";
    const GOLDEN_TASK_BINDING: &str =
        "5555555555555555555555555555555555555555555555555555555555555555";
    const GOLDEN_ROOT_DIRECT_BINDING: &str =
        "6666666666666666666666666666666666666666666666666666666666666666";

    fn publisher() -> CapabilityLeaseRootPublisherEvidenceV1 {
        CapabilityLeaseRootPublisherEvidenceV1 {
            boot_id_sha256: GOLDEN_BOOT.to_string(),
            publisher_epoch: GOLDEN_EPOCH.to_string(),
            publisher_sequence: 10,
            root_journal_genesis_sha256: GOLDEN_ROOT_GENESIS.to_string(),
            epoch_proof_sha256: GOLDEN_EPOCH_PROOF.to_string(),
        }
    }

    fn task() -> CapabilityLeaseRootTaskContextV1 {
        CapabilityLeaseRootTaskContextV1 {
            opaque_task_context_token: GOLDEN_TASK_TOKEN.to_string(),
            prepare_request_id: GOLDEN_PREPARE_REQUEST.to_string(),
            prepare_canonical_request_sha256: GOLDEN_PREPARE_CANONICAL.to_string(),
            workflow_id: GOLDEN_WORKFLOW.to_string(),
            task_id: GOLDEN_TASK.to_string(),
            authenticated_task_binding_sha256: GOLDEN_TASK_BINDING.to_string(),
        }
    }

    fn golden_registration() -> CapabilityLeaseRootTaskRegistrationV1 {
        CapabilityLeaseRootTaskRegistrationV1::derive(
            CODEX.provider_id.to_string(),
            CODEX.agent_id.to_string(),
            CODEX.replay_namespace.to_string(),
            publisher(),
            task(),
            GOLDEN_ROOT_DIRECT_BINDING.to_string(),
        )
        .unwrap()
    }

    fn fixture_inbox(descriptor: &AgentDescriptor) -> DirectOperationBindingInbox {
        let stable_seed = DirectOperationStableSeed {
            schema: STABLE_SEED_SCHEMA.to_string(),
            provider_id: descriptor.provider_id.to_string(),
            agent_id: descriptor.agent_id.to_string(),
            task_id: GOLDEN_TASK.to_string(),
            provider_invocation_id_sha256: sha256_bytes(b"lease-provider-invocation"),
            provider_session_id_sha256: sha256_bytes(b"lease-provider-session"),
            subject_uid: 10_123,
            subject_selinux_domain_sha256: sha256_bytes(b"lease-aishell-domain"),
        };
        let invocation_id = stable_seed.invocation_id().unwrap();
        let binding = DirectOperationBinding {
            schema: BINDING_SCHEMA.to_string(),
            stable_seed,
            invocation_id,
            workflow_id_sha256: sha256_bytes(GOLDEN_WORKFLOW.as_bytes()),
            agent_identity_key_sha256: descriptor.identity_key_sha256.to_string(),
            agent_executable_sha256: descriptor.identity_key_sha256.to_string(),
            authorized_adapter_set:
                crate::direct_operation::DirectOperationAuthorizedAdapterSetV3::p0_system_api(),
            attempt: DirectOperationProviderAttempt::derive(
                sha256_bytes(b"lease-runtime-lifecycle"),
                1,
                sha256_bytes(b"lease-daemon-attempt-context"),
            )
            .unwrap(),
        };
        let binding_sha256 = binding.digest_sha256().unwrap();
        DirectOperationBindingInbox {
            schema: BINDING_INBOX_SCHEMA.to_string(),
            binding,
            binding_sha256,
        }
    }

    fn assert_code<T>(expected: &'static str, result: CapabilityLeaseRootRegistrationResult<T>) {
        match result {
            Ok(_) => panic!("expected root task-registration rejection"),
            Err(error) => assert_eq!(error.code(), expected),
        }
    }

    #[test]
    fn generated_contract_hash_and_closed_status_are_exact() {
        assert_eq!(
            sha256_bytes(include_bytes!(
                "../contracts/capability-lease-root-registration-v1.json"
            )),
            CONTRACT_SHA256
        );
        assert_eq!(BINDING_FIELDS.len(), 18);
        assert_eq!(PAYLOAD_FIELDS.len(), 17);
        assert!(!TRANSPORT_AVAILABLE);
        assert!(!RUNTIME_CONSUMER_AVAILABLE);
        assert!(!CONFERS_EFFECT_AUTHORITY);
    }

    #[test]
    fn cross_language_golden_binding_is_byte_exact() {
        let registration = golden_registration();
        assert_eq!(
            registration.opaque_token_sha256().unwrap(),
            GOLDEN_OPAQUE_TOKEN_SHA256
        );
        assert_eq!(
            registration.binding_sha256().unwrap(),
            GOLDEN_REGISTRATION_BINDING_SHA256
        );
        let value = serde_json::to_value(&registration).unwrap();
        let fields = value
            .as_object()
            .unwrap()
            .keys()
            .map(String::as_str)
            .collect::<BTreeSet<_>>();
        assert_eq!(fields, PAYLOAD_FIELDS.iter().copied().collect());
    }

    #[test]
    fn direct_inbox_producer_binds_codex_without_authority() {
        for descriptor in [&CODEX] {
            let inbox = fixture_inbox(descriptor);
            let registration =
                derive_system_api_open_uri_root_task_registration(&inbox, publisher(), task())
                    .unwrap();
            assert_eq!(registration.provider_id, descriptor.provider_id);
            assert_eq!(registration.agent_id, descriptor.agent_id);
            assert_eq!(registration.replay_namespace, descriptor.replay_namespace);
            assert_eq!(
                registration.root_direct_binding_sha256,
                inbox.binding_sha256
            );
            registration.validate_for_inbox(&inbox).unwrap();
        }
    }

    #[test]
    fn retained_payload_rejects_descriptor_publisher_task_and_binding_drift() {
        let valid = golden_registration();

        let mut descriptor = valid.clone();
        descriptor.replay_namespace = "unregistered-replay-namespace".to_string();
        assert_code(
            "capability_lease_root_registration_descriptor_denied",
            descriptor.validate(),
        );

        let mut publisher = valid.clone();
        publisher.publisher_sequence = 0;
        assert_code(
            "capability_lease_root_registration_publisher_denied",
            publisher.validate(),
        );

        let mut task = valid.clone();
        task.opaque_task_context_token =
            format!("{}{}", OPAQUE_TASK_CONTEXT_TOKEN_PREFIX, "0".repeat(64));
        assert_code(
            "capability_lease_root_registration_task_denied",
            task.validate(),
        );

        let mut binding = valid;
        binding.registration_binding_sha256 = sha256_bytes(b"drifted-registration");
        assert_code(
            "capability_lease_root_registration_binding_denied",
            binding.validate(),
        );
    }

    #[test]
    fn direct_inbox_producer_rejects_workflow_task_and_binding_drift() {
        let inbox = fixture_inbox(&CODEX);

        let mut workflow = task();
        workflow.workflow_id = "req-fedcba9876543210fedcba9876543210".to_string();
        assert_code(
            "capability_lease_root_registration_inbox_denied",
            derive_system_api_open_uri_root_task_registration(&inbox, publisher(), workflow),
        );

        let mut task_id = task();
        task_id.task_id = "task.other".to_string();
        assert_code(
            "capability_lease_root_registration_inbox_denied",
            derive_system_api_open_uri_root_task_registration(&inbox, publisher(), task_id),
        );

        let registration =
            derive_system_api_open_uri_root_task_registration(&inbox, publisher(), task()).unwrap();
        let mut other = fixture_inbox(&CODEX);
        other.binding.stable_seed.agent_id = "unregistered-agent".to_string();
        assert_code(
            "capability_lease_root_registration_inbox_denied",
            registration.validate_for_inbox(&other),
        );
    }

    #[test]
    fn serde_rejects_unknown_payload_fields() {
        let mut value = serde_json::to_value(golden_registration()).unwrap();
        value
            .as_object_mut()
            .unwrap()
            .insert("effect_authority".to_string(), serde_json::json!(true));
        assert!(serde_json::from_value::<CapabilityLeaseRootTaskRegistrationV1>(value).is_err());
    }
}
