// @generated by tools/generate-direct-agent-host-abi.py; do not edit.

pub const CONTRACT_SCHEMA: &str = "org.trillionnium.direct-agent-host.abi-contract.v1";
pub const CONTRACT_SHA256: &str =
    "d538ef22f6ff1fcc5cf2ff15a158a8227631991bf83c3676ab19a66fce162c11";
pub const ABI_SCHEMA: &str = "org.trillionnium.direct-agent-host.abi.v1";
pub const TASK_LIFECYCLE_SCHEMA: &str = "org.trillionnium.direct-agent-host.task-lifecycle.v1";
pub const DIRECT_RESULT_SCHEMA: &str = "org.trillionnium.direct-agent-host.direct-result.v1";
pub const DIRECT_RECEIPT_SCHEMA: &str = "trillionnium.agent-direct-receipt.v2";

pub const BUILTIN_ANDROID_PROTOCOL: &str = "trillionnium.direct-agent-host.uds.v1";
pub const BUILTIN_ANDROID_SOCKET: &str = "trillionnium-direct-agent-host-v1";
pub const BUILTIN_ANDROID_TRUST_DOMAIN: &str = "android_aishell_peercred_peersec";
pub const BUILTIN_WIRE_METHOD_HEALTH: &str = "health";
pub const BUILTIN_WIRE_METHOD_RUN_DIRECT_TURN: &str = "plan";
pub const BUILTIN_WIRE_METHOD_CANCEL_TASK: &str = "cancel";

pub const KERNEL_AGENT_API_PROTOCOL: &str = "trillionnium.agent-api.uds.v2";
pub const KERNEL_AGENT_API_SOCKET: &str = "/run/trillionnium/agent-api-v2.sock";
pub const KERNEL_AGENT_API_TRUST_DOMAIN: &str = "kernel_peercred_peersec_channel_binding";
pub const KERNEL_WIRE_METHOD_HEALTH: &str = "health";
pub const KERNEL_WIRE_METHOD_CREATE_TASK: &str = "create_task";
pub const KERNEL_WIRE_METHOD_CANCEL_TASK: &str = "cancel_task";

pub const SHARED_LIFECYCLE_METHODS: &[&str] = &["health", "create_task", "cancel_task"];
pub const TASK_STATES: &[&str] = &[
    "created",
    "running",
    "waiting_for_approval",
    "indeterminate",
    "completed",
    "failed",
    "cancelled",
];
pub const TERMINAL_TASK_STATES: &[&str] = &["indeterminate", "completed", "failed", "cancelled"];
pub const DIRECT_OUTCOMES: &[&str] = &["completed", "indeterminate", "refused", "no_action"];
pub const DIRECT_RESULT_FIELDS: &[&str] = &[
    "direct_agent_host_abi",
    "direct_agent_host_abi_sha256",
    "direct_result_schema",
    "task_id",
    "direct_execution_receipt_id",
    "direct_execution_receipt_sha256",
    "direct_receipt_commitment",
    "plan_id",
    "approval_id",
    "action",
    "summary",
    "model",
    "provider_id",
    "provider",
    "provider_output_sha256",
    "agent_id",
    "agent_manifest_sha256",
    "agent_executable_sha256",
    "runtime_lifecycle_binding_sha256",
    "request_payload_sha256",
    "workflow_id_sha256",
    "direct_evidence_sha256",
    "direct_call_evidence",
    "direct_outcome",
    "direct_refusal_reason",
    "direct_refusal_sha256",
    "execution_mode",
    "requires_approval",
    "execution_available",
    "execution_completed",
    "network_scope",
    "tool_invocation_owned_by_agent",
    "tool_backend_owned_by_os",
    "daemon_is_effect_executor",
    "contract_confers_effect_authority",
    "model_invoked_tools",
    "model_executed_tools",
    "direct_tool_call_events",
    "completed_direct_tool_calls",
    "direct_tool_names",
    "plan_submitted_for_execution",
    "authority_called",
    "plan_latency_ms",
    "egress_grant_consumed",
];
pub const DIRECT_COMMITMENT_FIELDS: &[&str] = &[
    "schema",
    "direct_agent_host_abi",
    "direct_agent_host_abi_sha256",
    "direct_result_schema",
    "request_id_sha256",
    "request_payload_sha256",
    "subject_uid",
    "subject_selinux_domain_sha256",
    "provider_id",
    "workflow_id_sha256",
    "task_id",
    "agent_id",
    "agent_manifest_sha256",
    "agent_executable_sha256",
    "runtime_lifecycle_binding_sha256",
    "runtime_provider",
    "model",
    "summary_sha256",
    "provider_output_sha256",
    "direct_evidence_sha256",
    "direct_call_evidence",
    "direct_outcome",
    "direct_refusal_sha256",
    "direct_tool_call_events",
    "completed_direct_tool_calls",
    "direct_tool_names",
    "shell_exec_authorization_sha256",
    "shell_exec_direct_binding_sha256",
    "p01_daemon_build_binding_sha256",
];

pub const TOOL_INVOCATION_OWNED_BY_AGENT: bool = true;
pub const TOOL_BACKEND_OWNED_BY_OS: bool = true;
pub const DAEMON_IS_EFFECT_EXECUTOR: bool = false;
pub const CONTRACT_CONFERS_EFFECT_AUTHORITY: bool = false;

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DirectOutcome {
    Completed,
    Indeterminate,
    Refused,
    NoAction,
}

impl DirectOutcome {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Completed => "completed",
            Self::Indeterminate => "indeterminate",
            Self::Refused => "refused",
            Self::NoAction => "no_action",
        }
    }
}

pub fn bind_direct_result_contract(result: &mut serde_json::Map<String, serde_json::Value>) {
    result.insert(
        "direct_agent_host_abi".to_string(),
        serde_json::json!(ABI_SCHEMA),
    );
    result.insert(
        "direct_agent_host_abi_sha256".to_string(),
        serde_json::json!(CONTRACT_SHA256),
    );
    result.insert(
        "direct_result_schema".to_string(),
        serde_json::json!(DIRECT_RESULT_SCHEMA),
    );
    result.insert(
        "tool_invocation_owned_by_agent".to_string(),
        serde_json::json!(TOOL_INVOCATION_OWNED_BY_AGENT),
    );
    result.insert(
        "tool_backend_owned_by_os".to_string(),
        serde_json::json!(TOOL_BACKEND_OWNED_BY_OS),
    );
    result.insert(
        "daemon_is_effect_executor".to_string(),
        serde_json::json!(DAEMON_IS_EFFECT_EXECUTOR),
    );
    result.insert(
        "contract_confers_effect_authority".to_string(),
        serde_json::json!(CONTRACT_CONFERS_EFFECT_AUTHORITY),
    );
}

pub fn health_contract() -> serde_json::Value {
    serde_json::json!({
        "abi_schema": ABI_SCHEMA,
        "abi_contract_sha256": CONTRACT_SHA256,
        "task_lifecycle_schema": TASK_LIFECYCLE_SCHEMA,
        "direct_result_schema": DIRECT_RESULT_SCHEMA,
        "direct_receipt_schema": DIRECT_RECEIPT_SCHEMA,
        "shared_lifecycle_methods": SHARED_LIFECYCLE_METHODS,
        "task_states": TASK_STATES,
        "terminal_task_states": TERMINAL_TASK_STATES,
        "direct_outcomes": DIRECT_OUTCOMES,
        "carriers": {
            "builtin_android": {
                "protocol": BUILTIN_ANDROID_PROTOCOL,
                "trust_domain": BUILTIN_ANDROID_TRUST_DOMAIN,
                "declares_direct_turn_method": true,
                "implementation_status": "source_contract_only_materialization_hold",
                "runtime_ready": false,
            },
            "kernel_agent_api": {
                "protocol": KERNEL_AGENT_API_PROTOCOL,
                "trust_domain": KERNEL_AGENT_API_TRUST_DOMAIN,
                "declares_direct_turn_method": false,
                "implementation_status": "lifecycle_carrier_only_no_direct_turn",
                "runtime_ready": false,
            },
        },
        "tool_invocation_owned_by_agent": TOOL_INVOCATION_OWNED_BY_AGENT,
        "tool_backend_owned_by_os": TOOL_BACKEND_OWNED_BY_OS,
        "daemon_is_effect_executor": DAEMON_IS_EFFECT_EXECUTOR,
        "contract_confers_effect_authority": CONTRACT_CONFERS_EFFECT_AUTHORITY,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::TaskStatus;

    #[test]
    fn generated_contract_hash_is_exact() {
        assert_eq!(
            crate::sha256_bytes(include_bytes!("../contracts/direct-agent-host-abi-v1.json")),
            CONTRACT_SHA256
        );
    }

    #[test]
    fn task_lifecycle_matches_the_shared_os_type() {
        let states = [
            TaskStatus::Created,
            TaskStatus::Running,
            TaskStatus::WaitingForApproval,
            TaskStatus::Indeterminate,
            TaskStatus::Completed,
            TaskStatus::Failed,
            TaskStatus::Cancelled,
        ]
        .into_iter()
        .map(|status| {
            serde_json::to_value(status)
                .unwrap()
                .as_str()
                .unwrap()
                .to_string()
        })
        .collect::<Vec<_>>();
        assert_eq!(states, TASK_STATES);
    }

    #[test]
    fn direct_outcomes_and_result_fields_are_closed() {
        assert_eq!(
            [
                DirectOutcome::Completed,
                DirectOutcome::Indeterminate,
                DirectOutcome::Refused,
                DirectOutcome::NoAction,
            ]
            .map(DirectOutcome::as_str),
            DIRECT_OUTCOMES
        );
        assert!(!DIRECT_RESULT_FIELDS.contains(&"tool_execution_owned_by_os"));
        assert!(DIRECT_RESULT_FIELDS.contains(&"tool_backend_owned_by_os"));
        assert!(DIRECT_RESULT_FIELDS.contains(&"contract_confers_effect_authority"));
        let mut result = serde_json::Map::new();
        bind_direct_result_contract(&mut result);
        assert_eq!(result.len(), 7);
        assert_eq!(result["direct_agent_host_abi"], ABI_SCHEMA);
        assert_eq!(result["direct_agent_host_abi_sha256"], CONTRACT_SHA256);
        assert_eq!(result["contract_confers_effect_authority"], false);
    }

    #[test]
    fn health_contract_is_shared_and_confers_no_effect_authority() {
        let health = health_contract();
        assert_eq!(health["abi_schema"], ABI_SCHEMA);
        assert_eq!(health["abi_contract_sha256"], CONTRACT_SHA256);
        assert_eq!(
            health["shared_lifecycle_methods"],
            serde_json::json!(SHARED_LIFECYCLE_METHODS)
        );
        assert_eq!(health["tool_invocation_owned_by_agent"], true);
        assert_eq!(health["tool_backend_owned_by_os"], true);
        assert_eq!(health["daemon_is_effect_executor"], false);
        assert_eq!(health["contract_confers_effect_authority"], false);
        assert_eq!(
            health["carriers"]["builtin_android"]["declares_direct_turn_method"],
            true
        );
        assert_eq!(
            health["carriers"]["builtin_android"]["runtime_ready"],
            false
        );
        assert_eq!(
            health["carriers"]["builtin_android"]["implementation_status"],
            "source_contract_only_materialization_hold"
        );
        assert_eq!(
            health["carriers"]["kernel_agent_api"]["runtime_ready"],
            false
        );
        assert_ne!(BUILTIN_ANDROID_TRUST_DOMAIN, KERNEL_AGENT_API_TRUST_DOMAIN);
    }
}
