#!/usr/bin/env python3
"""Generate Java bindings and byte-exact mirrors for root publication v1."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "contracts/capability-lease-root-publication-v1.json"


def reject_duplicates(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON field: {key}")
        result[key] = value
    return result


def load_contract(path: Path) -> tuple[dict[str, object], bytes, str]:
    raw = path.read_bytes()
    try:
        contract = json.loads(raw, object_pairs_hook=reject_duplicates)
    except (UnicodeDecodeError, json.JSONDecodeError, ValueError) as error:
        raise SystemExit(f"invalid root-publication contract: {error}") from error
    expected = {
        "contract_schema", "task_publication_schema", "task_publication_ack_schema",
        "source_status", "fixed", "authority", "framing", "encoding", "validation",
    }
    if not isinstance(contract, dict) or set(contract) != expected:
        raise SystemExit("root-publication contract top-level fields are not closed")
    if contract["contract_schema"] != "org.trillionnium.capabilitylease.root-publication.contract.v1":
        raise SystemExit("unexpected root-publication contract schema")
    authority = contract["authority"]
    if authority != {
        "listener_available": False,
        "runtime_consumer_available": False,
        "confers_effect_authority": False,
    }:
        raise SystemExit("root-publication authority must remain closed")
    return contract, raw, hashlib.sha256(raw).hexdigest()


def java_array(values: list[str]) -> str:
    return ",\n".join(f'            "{value}"' for value in values)


def render_java(contract: dict[str, object], digest: str) -> str:
    fixed = contract["fixed"]
    encoding = contract["encoding"]
    return f'''/*
 * SPDX-License-Identifier: Apache-2.0
 */

package org.trillionnium.platform.internal;

import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

// @generated by generate-capability-lease-root-publication.py; do not edit.
final class CapabilityLeaseRootPublicationBindingV1 {{
    static final String CONTRACT_SCHEMA = "{contract['contract_schema']}";
    static final String CONTRACT_SHA256 = "{digest}";
    static final String TASK_PUBLICATION_SCHEMA = "{contract['task_publication_schema']}";
    static final String TASK_PUBLICATION_ACK_SCHEMA = "{contract['task_publication_ack_schema']}";
    static final String SOURCE_STATUS = "{contract['source_status']}";
    static final String ROOT_REGISTRATION_CONTRACT_SHA256 =
            "{fixed['root_registration_contract_sha256']}";
    static final String PROTOCOL = "{fixed['protocol']}";
    static final String OPERATION = "{fixed['operation']}";
    static final String TRANSPORT_ROLE = "{fixed['transport_role']}";
    static final String TRANSPORT_SELINUX_DOMAIN = "{fixed['transport_selinux_domain']}";
    static final String TRANSPORT_EXECUTABLE_IDENTITY =
            "{fixed['transport_executable_identity']}";
    static final int MAXIMUM_PAYLOAD_BYTES = {contract['framing']['maximum_payload_bytes']};
    static final boolean LISTENER_AVAILABLE = false;
    static final boolean RUNTIME_CONSUMER_AVAILABLE = false;
    static final boolean CONFERS_EFFECT_AUTHORITY = false;

    private static final String PUBLICATION_BINDING_DOMAIN =
            "{fixed['publication_binding_domain']}";
    private static final String ACK_BINDING_DOMAIN = "{fixed['ack_binding_domain']}";
    private static final String[] PUBLICATION_BINDING_FIELDS = {{
{java_array(encoding['publication_binding_fields'])}
    }};
    private static final String[] PUBLICATION_PAYLOAD_FIELDS = {{
{java_array(encoding['publication_payload_fields'])}
    }};
    private static final String[] TRANSPORT_PEER_FIELDS = {{
{java_array(encoding['transport_peer_fields'])}
    }};
    private static final String[] ACK_BINDING_FIELDS = {{
{java_array(encoding['ack_binding_fields'])}
    }};
    private static final String[] ACK_PAYLOAD_FIELDS = {{
{java_array(encoding['ack_payload_fields'])}
    }};

    static String derivePublicationBinding(String providerId, String agentId,
            String replayNamespace, long transportPeerUid, long transportPeerGid,
            String transportPeerSelinuxDomain, String transportExecutableSha256,
            String bootIdSha256, String publisherEpoch, long publisherSequence,
            String rootJournalGenesisSha256, String epochProofSha256,
            String rootRecordSha256, String rootRecordProofSha256,
            String registrationBindingSha256) {{
        MessageDigest digest = newSha256();
        hashString(digest, "domain", PUBLICATION_BINDING_DOMAIN);
        hashString(digest, "publication_schema", TASK_PUBLICATION_SCHEMA);
        hashString(digest, "publication_contract_sha256", CONTRACT_SHA256);
        hashString(digest, "root_registration_contract_sha256",
                ROOT_REGISTRATION_CONTRACT_SHA256);
        hashString(digest, "protocol", PROTOCOL);
        hashString(digest, "operation", OPERATION);
        hashString(digest, "provider_id", providerId);
        hashString(digest, "agent_id", agentId);
        hashString(digest, "replay_namespace", replayNamespace);
        hashLong(digest, "transport_peer_uid", transportPeerUid);
        hashLong(digest, "transport_peer_gid", transportPeerGid);
        hashString(digest, "transport_peer_selinux_domain", transportPeerSelinuxDomain);
        hashString(digest, "transport_executable_sha256", transportExecutableSha256);
        hashString(digest, "boot_id_sha256", bootIdSha256);
        hashString(digest, "publisher_epoch", publisherEpoch);
        hashLong(digest, "publisher_sequence", publisherSequence);
        hashString(digest, "root_journal_genesis_sha256", rootJournalGenesisSha256);
        hashString(digest, "epoch_proof_sha256", epochProofSha256);
        hashString(digest, "root_record_sha256", rootRecordSha256);
        hashString(digest, "root_record_proof_sha256", rootRecordProofSha256);
        hashString(digest, "registration_binding_sha256", registrationBindingSha256);
        return lowerHex(digest.digest());
    }}

    static String deriveAckBinding(String publicationBindingSha256,
            String registrationBindingSha256, String tokenRecordSha256,
            String publisherEpoch, long publisherSequence, String rootRecordSha256,
            String rootRecordProofSha256) {{
        MessageDigest digest = newSha256();
        hashString(digest, "domain", ACK_BINDING_DOMAIN);
        hashString(digest, "publication_binding_sha256", publicationBindingSha256);
        hashString(digest, "registration_binding_sha256", registrationBindingSha256);
        hashString(digest, "token_record_sha256", tokenRecordSha256);
        hashString(digest, "publisher_epoch", publisherEpoch);
        hashLong(digest, "publisher_sequence", publisherSequence);
        hashString(digest, "root_record_sha256", rootRecordSha256);
        hashString(digest, "root_record_proof_sha256", rootRecordProofSha256);
        return lowerHex(digest.digest());
    }}

    static String[] publicationBindingFields() {{ return PUBLICATION_BINDING_FIELDS.clone(); }}
    static String[] publicationPayloadFields() {{ return PUBLICATION_PAYLOAD_FIELDS.clone(); }}
    static String[] transportPeerFields() {{ return TRANSPORT_PEER_FIELDS.clone(); }}
    static String[] ackBindingFields() {{ return ACK_BINDING_FIELDS.clone(); }}
    static String[] ackPayloadFields() {{ return ACK_PAYLOAD_FIELDS.clone(); }}

    private static void hashString(MessageDigest digest, String name, String value) {{
        if (value == null) throw new SecurityException("missing root-publication binding value");
        hashBytes(digest, name, value.getBytes(StandardCharsets.UTF_8));
    }}

    private static void hashLong(MessageDigest digest, String name, long value) {{
        if (value <= 0) throw new SecurityException("invalid root-publication integer");
        hashBytes(digest, name, ByteBuffer.allocate(Long.BYTES).putLong(value).array());
    }}

    private static void hashBytes(MessageDigest digest, String name, byte[] value) {{
        byte[] encodedName = name.getBytes(StandardCharsets.US_ASCII);
        digest.update(ByteBuffer.allocate(Integer.BYTES).putInt(encodedName.length).array());
        digest.update(encodedName);
        digest.update(ByteBuffer.allocate(Integer.BYTES).putInt(value.length).array());
        digest.update(value);
    }}

    private static MessageDigest newSha256() {{
        try {{
            return MessageDigest.getInstance("SHA-256");
        }} catch (NoSuchAlgorithmException impossible) {{
            throw new AssertionError("SHA-256 unavailable", impossible);
        }}
    }}

    private static String lowerHex(byte[] value) {{
        char[] alphabet = "0123456789abcdef".toCharArray();
        char[] encoded = new char[value.length * 2];
        for (int index = 0; index < value.length; index++) {{
            int item = value[index] & 0xff;
            encoded[index * 2] = alphabet[item >>> 4];
            encoded[index * 2 + 1] = alphabet[item & 0x0f];
        }}
        return new String(encoded);
    }}

    private CapabilityLeaseRootPublicationBindingV1() {{}}
}}
'''


def check_or_write(path: Path, expected: bytes, check: bool, label: str) -> None:
    if check:
        if not path.is_file() or path.read_bytes() != expected:
            raise SystemExit(f"generated {label} is stale: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(expected)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--contract", type=Path, default=CONTRACT)
    parser.add_argument("--java-output", type=Path)
    parser.add_argument("--mirror-output", type=Path, action="append", default=[])
    args = parser.parse_args()
    contract, raw, digest = load_contract(args.contract)
    if args.java_output is not None:
        check_or_write(args.java_output, render_java(contract, digest).encode(), args.check,
                       "Java root-publication binding")
    for mirror in args.mirror_output:
        check_or_write(mirror, raw, args.check, "root-publication contract mirror")


if __name__ == "__main__":
    main()
