---- MODULE EffectLifecycle ----
EXTENDS Naturals, Sequences, FiniteSets

(*
GENERATED byte-for-byte from docs/machine/effect-lifecycle.v1.json.
The Python verifier requires exact equality, explores the same ordinary and
crash-recovery relations, and CI executes TLC on this checked-in projection.
This remains L1 source evidence only; it is not target, device, fault, signing,
deployment, OTA, or public-release evidence.
*)

States == {
  "RECEIVED",
  "VALIDATED",
  "CAPACITY_RESERVED",
  "ACCEPTED_DURABLE",
  "EFFECT_ATTEMPTING",
  "EFFECT_STARTED_OBSERVED",
  "TERMINAL_OBSERVED",
  "TERMINAL_DURABLE",
  "DELIVERY_PENDING",
  "DELIVERED",
  "ACKNOWLEDGED",
  "REJECTED_BEFORE_EFFECT",
  "UNKNOWN_RECONCILIATION_REQUIRED",
  "FENCED",
  "CLOSED"
}

Edges == {
  <<"RECEIVED", "VALIDATED">>,
  <<"RECEIVED", "REJECTED_BEFORE_EFFECT">>,
  <<"VALIDATED", "CAPACITY_RESERVED">>,
  <<"VALIDATED", "REJECTED_BEFORE_EFFECT">>,
  <<"CAPACITY_RESERVED", "ACCEPTED_DURABLE">>,
  <<"CAPACITY_RESERVED", "REJECTED_BEFORE_EFFECT">>,
  <<"CAPACITY_RESERVED", "FENCED">>,
  <<"ACCEPTED_DURABLE", "EFFECT_ATTEMPTING">>,
  <<"ACCEPTED_DURABLE", "TERMINAL_OBSERVED">>,
  <<"ACCEPTED_DURABLE", "FENCED">>,
  <<"EFFECT_ATTEMPTING", "EFFECT_STARTED_OBSERVED">>,
  <<"EFFECT_ATTEMPTING", "TERMINAL_OBSERVED">>,
  <<"EFFECT_ATTEMPTING", "UNKNOWN_RECONCILIATION_REQUIRED">>,
  <<"EFFECT_STARTED_OBSERVED", "TERMINAL_OBSERVED">>,
  <<"EFFECT_STARTED_OBSERVED", "UNKNOWN_RECONCILIATION_REQUIRED">>,
  <<"TERMINAL_OBSERVED", "TERMINAL_DURABLE">>,
  <<"TERMINAL_OBSERVED", "UNKNOWN_RECONCILIATION_REQUIRED">>,
  <<"TERMINAL_DURABLE", "DELIVERY_PENDING">>,
  <<"DELIVERY_PENDING", "DELIVERED">>,
  <<"DELIVERY_PENDING", "DELIVERY_PENDING">>,
  <<"DELIVERED", "ACKNOWLEDGED">>,
  <<"DELIVERED", "DELIVERY_PENDING">>,
  <<"ACKNOWLEDGED", "CLOSED">>,
  <<"REJECTED_BEFORE_EFFECT", "CLOSED">>,
  <<"UNKNOWN_RECONCILIATION_REQUIRED", "TERMINAL_OBSERVED">>,
  <<"UNKNOWN_RECONCILIATION_REQUIRED", "FENCED">>,
  <<"FENCED", "CLOSED">>
}

RecoveryEdges == {
  <<"RECEIVED", "RECEIVED">>,
  <<"RECEIVED", "REJECTED_BEFORE_EFFECT">>,
  <<"VALIDATED", "RECEIVED">>,
  <<"VALIDATED", "VALIDATED">>,
  <<"VALIDATED", "REJECTED_BEFORE_EFFECT">>,
  <<"CAPACITY_RESERVED", "REJECTED_BEFORE_EFFECT">>,
  <<"CAPACITY_RESERVED", "FENCED">>,
  <<"ACCEPTED_DURABLE", "ACCEPTED_DURABLE">>,
  <<"ACCEPTED_DURABLE", "FENCED">>,
  <<"EFFECT_ATTEMPTING", "UNKNOWN_RECONCILIATION_REQUIRED">>,
  <<"EFFECT_ATTEMPTING", "FENCED">>,
  <<"EFFECT_STARTED_OBSERVED", "UNKNOWN_RECONCILIATION_REQUIRED">>,
  <<"EFFECT_STARTED_OBSERVED", "FENCED">>,
  <<"TERMINAL_OBSERVED", "TERMINAL_DURABLE">>,
  <<"TERMINAL_OBSERVED", "UNKNOWN_RECONCILIATION_REQUIRED">>,
  <<"TERMINAL_OBSERVED", "FENCED">>,
  <<"TERMINAL_DURABLE", "TERMINAL_DURABLE">>,
  <<"TERMINAL_DURABLE", "DELIVERY_PENDING">>,
  <<"DELIVERY_PENDING", "DELIVERY_PENDING">>,
  <<"DELIVERY_PENDING", "DELIVERED">>,
  <<"DELIVERED", "DELIVERY_PENDING">>,
  <<"DELIVERED", "DELIVERED">>,
  <<"DELIVERED", "ACKNOWLEDGED">>,
  <<"ACKNOWLEDGED", "ACKNOWLEDGED">>,
  <<"ACKNOWLEDGED", "CLOSED">>,
  <<"UNKNOWN_RECONCILIATION_REQUIRED", "UNKNOWN_RECONCILIATION_REQUIRED">>,
  <<"UNKNOWN_RECONCILIATION_REQUIRED", "FENCED">>,
  <<"FENCED", "FENCED">>,
  <<"FENCED", "CLOSED">>
}

EffectPossibleStates == {
  "EFFECT_ATTEMPTING",
  "EFFECT_STARTED_OBSERVED",
  "TERMINAL_OBSERVED",
  "TERMINAL_DURABLE",
  "DELIVERY_PENDING",
  "DELIVERED",
  "ACKNOWLEDGED",
  "UNKNOWN_RECONCILIATION_REQUIRED",
  "FENCED",
  "CLOSED"
}

EffectAdmissionStates == {"ACCEPTED_DURABLE", "EFFECT_ATTEMPTING", "EFFECT_STARTED_OBSERVED"}
DeliveryStates == {"DELIVERY_PENDING", "DELIVERED", "ACKNOWLEDGED"}

VARIABLES state, accepted, attempted, terminalDurable, delivered, acknowledged,
          recoveryLocked, automaticRedispatch

vars == <<state, accepted, attempted, terminalDurable, delivered, acknowledged,
          recoveryLocked, automaticRedispatch>>

Init ==
  /\ state = "RECEIVED"
  /\ accepted = FALSE
  /\ attempted = FALSE
  /\ terminalDurable = FALSE
  /\ delivered = FALSE
  /\ acknowledged = FALSE
  /\ recoveryLocked = FALSE
  /\ automaticRedispatch = FALSE

OrdinaryNext ==
  \E edge \in Edges:
    /\ edge[1] = state
    /\ state' = edge[2]
    /\ accepted' = (accepted \/ edge[2] = "ACCEPTED_DURABLE")
    /\ attempted' = (attempted \/ edge = <<"ACCEPTED_DURABLE", "EFFECT_ATTEMPTING">>)
    /\ terminalDurable' = (terminalDurable \/ edge[2] = "TERMINAL_DURABLE")
    /\ delivered' = (delivered \/ edge[2] = "DELIVERED")
    /\ acknowledged' = (acknowledged \/ edge[2] = "ACKNOWLEDGED")
    /\ recoveryLocked' = recoveryLocked
    /\ automaticRedispatch' = FALSE

RecoveryNext ==
  \E edge \in RecoveryEdges:
    /\ edge[1] = state
    /\ state' = edge[2]
    /\ accepted' = (accepted \/ edge[2] = "ACCEPTED_DURABLE")
    /\ attempted' = attempted
    /\ terminalDurable' = (terminalDurable \/ edge[2] = "TERMINAL_DURABLE")
    /\ delivered' = (delivered \/ edge[2] = "DELIVERED")
    /\ acknowledged' = (acknowledged \/ edge[2] = "ACKNOWLEDGED")
    /\ recoveryLocked' = (recoveryLocked \/ edge[1] \in EffectPossibleStates \/ edge[2] \in {"UNKNOWN_RECONCILIATION_REQUIRED", "FENCED"})
    /\ automaticRedispatch' = FALSE

Next == OrdinaryNext \/ RecoveryNext

TypeOK ==
  /\ state \in States
  /\ accepted \in BOOLEAN
  /\ attempted \in BOOLEAN
  /\ terminalDurable \in BOOLEAN
  /\ delivered \in BOOLEAN
  /\ acknowledged \in BOOLEAN
  /\ recoveryLocked \in BOOLEAN
  /\ automaticRedispatch \in BOOLEAN

NoAutomaticRedispatch == automaticRedispatch = FALSE

EffectRequiresDurableAcceptance ==
  (state \in {"EFFECT_ATTEMPTING", "EFFECT_STARTED_OBSERVED"}) => accepted

DeliveryRequiresDurableTerminal ==
  (state \in DeliveryStates) => terminalDurable

AcknowledgementRequiresDelivery ==
  (state = "ACKNOWLEDGED") => delivered

NoEffectReadmissionAfterUncertainRecovery ==
  recoveryLocked => state \notin EffectAdmissionStates

Spec == Init /\ [][Next]_vars

====
