#!/usr/bin/env python3
"""Generate codec-only owner-open protocol constants from the r3 contract.

The generator deliberately emits no allow/deny table, risk classifier,
approval rule, executable allowlist, ADB subcommand catalog, or fixed runtime
identity. Those semantics belong to Codex/owner configuration, not this codec.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

DEFAULT_CONTRACT = Path("docs/contracts/codex-sovereign-direct-tools-v1.json")
DEFAULT_OUTPUT = Path("crates/trillionnium-owner-open-types/src/generated.rs")


def load_contract(path: Path) -> dict[str, object]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("owner-open contract must be a JSON object")
    required = {
        "schema",
        "revision",
        "profiles",
        "ingress",
        "request_schemas",
        "run_turn_frame",
    }
    missing = sorted(required.difference(value))
    if missing:
        raise ValueError(f"owner-open contract is missing keys: {', '.join(missing)}")
    profiles = value["profiles"]
    ingress = value["ingress"]
    if not isinstance(profiles, dict) or "owner_open" not in profiles:
        raise ValueError("owner-open contract has no profiles.owner_open")
    if not isinstance(ingress, dict):
        raise ValueError("owner-open contract ingress must be an object")
    for key in ("default_socket", "rootlinux_alias", "owner_open_request_type"):
        if not isinstance(ingress.get(key), str) or not ingress[key]:
            raise ValueError(f"owner-open contract ingress.{key} must be a string")
    return value


def rust_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render(contract: dict[str, object]) -> str:
    ingress = contract["ingress"]
    assert isinstance(ingress, dict)
    values = {
        "CONTRACT_SCHEMA": contract["schema"],
        "CONTRACT_REVISION": contract["revision"],
        "DEFAULT_ANDROID_ABSTRACT_SOCKET": ingress["default_socket"],
        "DEFAULT_ROOT_LINUX_SOCKET_ALIAS": ingress["rootlinux_alias"],
        "DEFAULT_PROFILE_ID": "owner-open",
        "OWNER_OPEN_REQUEST_TYPE": ingress["owner_open_request_type"],
        # Shared provider/model event labels are transport constants only. They
        # carry no tool policy, admission rule or runtime identity.
        "FRAME_PROVIDER_STATUS": "provider.status",
        "FRAME_MODEL_DELTA": "model.delta",
        "FRAME_MODEL_MESSAGE": "model.message",
    }
    for name, value in values.items():
        if not isinstance(value, str):
            raise ValueError(f"{name} source value must be a string")
    lines = [
        "// @generated by tools/generate-owner-open-types.py; do not edit.",
        "",
    ]
    lines.extend(
        f"pub const {name}: &str = {rust_string(value)};" for name, value in values.items()
    )
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--contract", type=Path, default=DEFAULT_CONTRACT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        generated = render(load_contract(args.contract))
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"owner-open generation failed: {error}", file=sys.stderr)
        return 2

    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except OSError as error:
            print(f"owner-open generated output is unavailable: {error}", file=sys.stderr)
            return 1
        if current != generated:
            print(
                f"{args.output} is stale; run tools/generate-owner-open-types.py",
                file=sys.stderr,
            )
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
