#!/usr/bin/env python3
"""Generate the unselected owner-open Android package fragment from profile.json."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any

PROFILE = Path("android-integration/owner-open-profile/profile.json")
EXPECTED_SCHEMA = "org.trillionnium.owner-open.android-profile.v1"


class GenerationError(ValueError):
    pass


class DuplicateMember(ValueError):
    pass


def pairs(values: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in values:
        if key in result:
            raise DuplicateMember(f"duplicate key {key}")
        result[key] = value
    return result


def load(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=pairs)
    except (OSError, UnicodeDecodeError, json.JSONDecodeError, DuplicateMember) as error:
        raise GenerationError(f"cannot read owner-open Android profile: {error}") from error
    if not isinstance(value, dict) or value.get("schema") != EXPECTED_SCHEMA:
        raise GenerationError(f"profile schema must be {EXPECTED_SCHEMA}")
    return value


def render(profile: dict[str, Any]) -> str:
    activation = profile.get("activation")
    claims = profile.get("claims")
    modules = profile.get("required_product_modules")
    if not isinstance(activation, dict) or not isinstance(claims, dict):
        raise GenerationError("profile activation or claims are malformed")
    if activation.get("selected_in_current_product") is not False:
        raise GenerationError("source generator only accepts an unselected profile")
    if claims.get("image_included") is not False:
        raise GenerationError("source generator cannot generate an image-included claim")
    if not isinstance(modules, list) or not modules:
        raise GenerationError("required_product_modules is empty")
    names: list[str] = []
    for item in modules:
        if not isinstance(item, dict):
            raise GenerationError("product module entry must be an object")
        name = item.get("name")
        materialization = item.get("materialization")
        if not isinstance(name, str) or not name or any(ch.isspace() for ch in name):
            raise GenerationError("product module name is malformed")
        if materialization != "UNBOUND_SOONG_MODULE":
            raise GenerationError(
                "unselected source profile must retain UNBOUND_SOONG_MODULE truth"
            )
        names.append(name)
    if len(names) != len(set(names)):
        raise GenerationError("product module names are duplicated")
    lines = [
        "# AUTO-GENERATED by tools/generate-owner-open-android-profile.py.",
        "# SOURCE CONTRACT ONLY: do not include until every module is bound and", 
        "# tools/verify-owner-open-android-profile.py --strict passes.",
        "# profile_id: " + str(profile.get("profile_id")),
        "",
        "PRODUCT_PACKAGES += \\",
    ]
    for index, name in enumerate(names):
        suffix = " \\\" if index + 1 < len(names) else ""
        lines.append(f"    {name}{suffix}")
    lines.extend(
        [
            "",
            "# No Authority, lease, P01 custody, old shell broker or semantic ADB",
            "# package may be appended to this owner-open profile.",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    try:
        profile = load(args.root / PROFILE)
        output = args.root / profile["activation"]["product_make_fragment"]
        rendered = render(profile)
        if args.check:
            try:
                current = output.read_text(encoding="utf-8")
            except OSError as error:
                raise GenerationError(f"generated fragment is missing: {error}") from error
            if current != rendered:
                raise GenerationError("generated owner-open Android fragment has drifted")
            print("PASS_OWNER_OPEN_ANDROID_PROFILE_GENERATED")
            return 0
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered, encoding="utf-8")
        print(output)
        return 0
    except (KeyError, TypeError, GenerationError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
